apiVersion: v1
kind: ConfigMap
metadata:
  name: goose-slackbot-config
  namespace: goose-slackbot
data:
  # Application Configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "3000"
  WORKERS: "4"
  
  # Database Configuration
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  
  # Redis Configuration
  REDIS_SESSION_TTL: "7200"
  REDIS_CACHE_TTL: "3600"
  
  # Goose Integration
  GOOSE_MCP_SERVER_URL: "http://goose-mcp-service:8000"
  GOOSE_MCP_TIMEOUT: "300"
  GOOSE_MAX_CONCURRENT_QUERIES: "20"
  
  # Snowflake Configuration
  SNOWFLAKE_WAREHOUSE: "COMPUTE_WH"
  SNOWFLAKE_DATABASE: "ANALYTICS"
  SNOWFLAKE_SCHEMA: "PUBLIC"
  
  # Authentication Configuration
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_HOURS: "24"
  
  # Logging and Monitoring
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  
  # Application Limits
  MAX_RESULT_ROWS: "50000"
  MAX_INLINE_ROWS: "20"
  QUERY_TIMEOUT_SECONDS: "600"
  MAX_FILE_SIZE_MB: "100"
  ALLOWED_FILE_TYPES: "csv,xlsx,json"
  
  # Rate Limiting
  RATE_LIMIT_PER_USER_PER_MINUTE: "20"
  RATE_LIMIT_GLOBAL_PER_MINUTE: "500"
  
  # Feature Flags
  ENABLE_QUERY_HISTORY: "true"
  ENABLE_QUERY_SHARING: "true"
  ENABLE_INTERACTIVE_BUTTONS: "true"
  ENABLE_FILE_UPLOADS: "true"
  ENABLE_THREAD_MANAGEMENT: "true"
  ENABLE_USER_PERMISSIONS: "true"
  
  # Optional Services
  SLACK_ADMIN_CHANNEL: "#goose-admin"
  LDAP_SERVER: ""
  LDAP_BASE_DN: ""
  LDAP_BIND_USER: ""
  USER_MAPPING_SERVICE_URL: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: goose-slackbot
data:
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: goose-slackbot
data:
  redis.conf: |
    # Redis Configuration for Goose Slackbot
    bind 0.0.0.0
    port 6379
    timeout 0
    keepalive 300
    
    # Memory management
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Security
    requirepass ${REDIS_PASSWORD}
    
    # Logging
    loglevel notice
    
    # Performance
    tcp-backlog 511
    databases 16
