apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: goose-slackbot-hpa
  namespace: goose-slackbot
  labels:
    app: goose-slackbot
    component: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goose-slackbot-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics scaling (if available)
  - type: Pods
    pods:
      metric:
        name: slack_requests_per_second
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# Vertical Pod Autoscaler (VPA) - Optional
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: goose-slackbot-vpa
  namespace: goose-slackbot
  labels:
    app: goose-slackbot
    component: app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goose-slackbot-app
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Initial, Recreation, Auto
  resourcePolicy:
    containerPolicies:
    - containerName: app
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goose-slackbot-pdb
  namespace: goose-slackbot
  labels:
    app: goose-slackbot
    component: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: goose-slackbot
      component: app

---
# Database Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: goose-slackbot
  labels:
    app: goose-slackbot
    component: postgres
spec:
  maxUnavailable: 0  # Database should not be disrupted
  selector:
    matchLabels:
      app: goose-slackbot
      component: postgres
