name: Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-public.txt
          pip install -r tests/requirements.txt
      
      - name: Run linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests
        run: |
          pytest tests/unit/ -v --tb=short
      
      - name: Run integration tests
        run: |
          pytest tests/integration/ -v --tb=short
        env:
          ENVIRONMENT: test
          GOOSE_MODE: mock
          DATABASE_URL: sqlite:///test.db
          REDIS_URL: redis://localhost:6379

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: false
      
      - name: Run database migrations
        run: |
          heroku run python scripts/db_migrate.py up --app ${{secrets.HEROKU_APP_NAME}}
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      
      - name: Health check
        run: |
          sleep 10
          curl -f https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health || exit 1
      
      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "App URL: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "Check logs: heroku logs --tail --app ${{secrets.HEROKU_APP_NAME}}"
